// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwZ8KvzW_um5oz5PIHN11Y8QdcviZEvW8',
    appId: '1:448212659414:web:7164cd510ca28d31106d77',
    messagingSenderId: '448212659414',
    projectId: 'reganappsmachinetest',
    authDomain: 'reganappsmachinetest.firebaseapp.com',
    storageBucket: 'reganappsmachinetest.appspot.com',
    measurementId: 'G-SW2MG71P3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8VxzF90nxuHrvxPkJsZoZh1xrIf9eKkA',
    appId: '1:448212659414:android:faecbb91fc7c2a6b106d77',
    messagingSenderId: '448212659414',
    projectId: 'reganappsmachinetest',
    storageBucket: 'reganappsmachinetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5Z6yxO-W2FU4aU8jXtyl4E0Cmq8tBBA',
    appId: '1:448212659414:ios:14c044cfed58dbb1106d77',
    messagingSenderId: '448212659414',
    projectId: 'reganappsmachinetest',
    storageBucket: 'reganappsmachinetest.appspot.com',
    iosBundleId: 'com.example.reganappsMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5Z6yxO-W2FU4aU8jXtyl4E0Cmq8tBBA',
    appId: '1:448212659414:ios:14c044cfed58dbb1106d77',
    messagingSenderId: '448212659414',
    projectId: 'reganappsmachinetest',
    storageBucket: 'reganappsmachinetest.appspot.com',
    iosBundleId: 'com.example.reganappsMachineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwZ8KvzW_um5oz5PIHN11Y8QdcviZEvW8',
    appId: '1:448212659414:web:3e7dce9630a4ed29106d77',
    messagingSenderId: '448212659414',
    projectId: 'reganappsmachinetest',
    authDomain: 'reganappsmachinetest.firebaseapp.com',
    storageBucket: 'reganappsmachinetest.appspot.com',
    measurementId: 'G-70Z30HGKCC',
  );
}
